name: cems
description: Course Enrollment Management System - A Dart console application for managing students, courses, and enrollments
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

# dependencies:
#   Add any dependencies here if needed

dev_dependencies:
  lints: ^3.0.0

